application:
  name: hasura
  project: hasura
  organization: QoveryCommunity
  publicly_accessible: true
databases:
- type: postgresql
  version: "12"
  name: my-postgresql-database
routers:
- name: main
  routes:
  - application_name: hasura
    paths:
    - /*
